version: 0.2
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPO_URI
  build:
    commands:
      - docker build --platform linux/amd64 --build-arg BASE_IMAGE=$BASE_IMAGE -t $REPO_URI:$BASE_IMAGE .
  post_build:
    commands:
      - docker push $REPO_URI:$BASE_IMAGE
      - >-
        aws events put-events --entries
        "[{\"Source\":\"ecs-runner\",\"DetailType\":\"image-build\",\"Detail\":\"{\\\"build_id\\\":\\\"$CODEBUILD_BUILD_ID\\\",\\\"image_uri\\\":\\\"$REPO_URI:$BASE_IMAGE\\\",\\\"status\\\":\\\"SUCCEEDED\\\"}\",\"EventBusName\":\"$EVENT_BUS_NAME\"}]"
artifacts:
  files: []
