name: ECS Runner Test

on:
  workflow_dispatch:

jobs:
  run-on-ecs:
    runs-on: [self-hosted, image:ubuntu:22.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run sample job
        run: echo "Hello from ECS self-hosted runner"
